-- Ben's collection import from Vinyl Cat 30.12.25.xlsx
-- 526 records

INSERT INTO public.collection (username, artist, album)
VALUES
  ('Ben', '22-20''s', '05 03'),
  ('Ben', '86 TVs', '86 TVs (Ltd Ed D2C Excl incl 7")'),
  ('Ben', '86 TVs', 'You Don''t Have To Be Yourself Right Now EP'),
  ('Ben', 'A-ha', 'Sun always shines on TV'),
  ('Ben', 'A-ha', 'Take on me'),
  ('Ben', 'Adorable', 'Against Perfection (30th Ann Ed - Ltd Ed)'),
  ('Ben', 'Adorable', 'Fake'),
  ('Ben', 'Adorable', 'Sunshine Smile'),
  ('Ben', 'Adultnet', 'August'),
  ('Ben', 'Ainslie Wills', 'All You Have Is All You Need (Signed)'),
  ('Ben', 'Airhead', 'Counting Sheep'),
  ('Ben', 'Airhead', 'Funny how'),
  ('Ben', 'Airhead', 'That''s Enough – EP'),
  ('Ben', 'Alex The Astronaut', 'The Theory of Absolutely Nothing (Signed)'),
  ('Ben', 'Angie McMahon', 'Piano Salt (Ltd Green vinyl)'),
  ('Ben', 'Angie McMahon', 'Salt - Ltd blue vinyl'),
  ('Ben', 'Angie McMahon', 'Light Dark Light Again (Dark Blue vinyl with Excl Tour O Card)'),
  ('Ben', 'Angie McMahon', 'Light Dark Light Again (Transparent Blue vinyl with Excl Tour O Card)'),
  ('Ben', 'Angie McMahon', 'Light Dark Light Again (Transparent Green indie vinyl with Excl Tour O Card)'),
  ('Ben', 'Angus & Julia Stone', 'Chocolates & Cigarettes EP'),
  ('Ben', 'Arcade Fire', 'Funeral'),
  ('Ben', 'Arcade Fire', 'Reflektor'),
  ('Ben', 'Athlete', 'Beyond The Neigbourhood x3'),
  ('Ben', 'Athlete – Tourist Dinked Edition Ltd Ed 1', '000'),
  ('Ben', 'Athlete', 'The Getaway'),
  ('Ben', 'Athlete', 'Vehicles & Animals (20th Ann'' 2LP Dlx Blue Vinyl)'),
  ('Ben', 'Athlete', 'You got the style'),
  ('Ben', 'Augustus Pablo', 'King Tubbys Meets Rockers Uptown'),
  ('Ben', 'Badly Drawn Boy', 'Banana Skin Shoes'),
  ('Ben', 'Badly Drawn Boy', 'Nothing''s Gonna Change Your Mind (Promo)'),
  ('Ben', 'Badly Drawn Boy', 'Promises (Remixes)'),
  ('Ben', 'Badly Drawn Boy', 'Welcome to the Overground (Promo)'),
  ('Ben', 'BC Camplight', 'A Sober Conversation (Gold LP)'),
  ('Ben', 'BC Camplight', 'Shortly After Take Off'),
  ('Ben', 'BC Camplight', 'The Last Rotation of Earth (Cream Vinyl)'),
  ('Ben', 'Belle & Sebastian', 'If You''re Feeling Sinister'),
  ('Ben', 'Ben Howard', 'Collections from the Whiteout (2xColoured LP - transparent)'),
  ('Ben', 'Ben Howard', 'How Are You Feeling? (12" feat prev unreleased I Forget…Alb tracks)'),
  ('Ben', 'Ben Howard', 'I Forget Where We Were'),
  ('Ben', 'Ben Howard', 'Is It? (Blue Vinyl)'),
  ('Ben', 'Ben Howard', 'Noonday Dream'),
  ('Ben', 'Bernard Butler', 'People Move On 2 LP (RSD ''21)'),
  ('Ben', 'Beth Orton', 'Central Reservation'),
  ('Ben', 'Beth Orton', 'Central Reservation (RSD 22 Red Vinyl)'),
  ('Ben', 'Beth Orton', 'Trailer Park (RSD 22 Ltd Ed Blue vinyl)'),
  ('Ben', 'Beth Orton', 'Weather Alive (Ltd Ed Transparent vinyl)'),
  ('Ben', 'Billy Bragg', 'Life''s A Riot With Spy Vs Spy'),
  ('Ben', 'Blackboard Jungle Dub', 'The Upsetters'),
  ('Ben', 'Blink', 'Going to Nepal'),
  ('Ben', 'Blink', 'Its not my fault (white label)'),
  ('Ben', 'Blueburn', 'Got to know you'),
  ('Ben', 'Blur', 'Modern Life is Rubbish'),
  ('Ben', 'Blur', 'Music is my radar (while label)'),
  ('Ben', 'Blur', 'The Ballad of Darren - Limited edition clear and black deluxe marbled vinyl housed in a gatefold outer sleeve, includes an exclusive poster and a 12 page booklet, 7" black vinyl in picture sleeve featuring two bonus tracks and deluxe 12-track CD in card sleeve, all contained inside inner gatefold'),
  ('Ben', 'Blur', 'Think Tank (2 x vinyl Reissue Spec Ed 2012)'),
  ('Ben', 'Bombay Bicycle Club', 'A Different Kind of Fix'),
  ('Ben', 'Bombay Bicycle Club', 'Everything Else Has Gone Wrong'),
  ('Ben', 'Bombay Bicycle Club', 'My Big Day (Indie Pink Vinyl)'),
  ('Ben', 'Bombay Bicycle Club', 'So Long, See You Tomorrow'),
  ('Ben', 'Bronski Beat', 'Hit that perfect beat (single)'),
  ('Ben', 'Carpenters', 'The Singles 1969-1973'),
  ('Ben', 'Cast', 'Sandstorm'),
  ('Ben', 'Cherry Ghost', 'Thirst For Romance (15th Ann Pressing)'),
  ('Ben', 'Cocteau Twins', 'Four-Calendar Café'),
  ('Ben', 'Cocteau Twins', 'Heaven or Las Vegas'),
  ('Ben', 'Coldplay', 'Clocks (Remixes) x4'),
  ('Ben', 'Coldplay', 'Don''t Panic'),
  ('Ben', 'Coldplay', 'In My Place'),
  ('Ben', 'Coldplay', 'Speed of Sound x2'),
  ('Ben', 'Coldplay', 'Talk (Remixes)'),
  ('Ben', 'Coldplay', 'Talk (Remixes) Promo x6'),
  ('Ben', 'Coldplay', 'Trouble'),
  ('Ben', 'Coldplay', 'X&Y x2'),
  ('Ben', 'Coldplay', 'Yellow (Promo only) x7'),
  ('Ben', 'Crowded House', 'Time on Earth x3'),
  ('Ben', 'Curtis Mayfield', 'Curtis'),
  ('Ben', 'Damien Rice', 'My Favourite Fantasy'),
  ('Ben', 'Damien Rice', 'O'),
  ('Ben', 'Dan Mangan', 'Oh Fortune (10th Ann Dlx Ed)'),
  ('Ben', 'David Gray', 'Best Of'),
  ('Ben', 'David Gray', 'Gold in A brass Age'),
  ('Ben', 'David Gray', 'Life in Slow Motion (Glacial Blue Ed'' 20th Ann'')'),
  ('Ben', 'David Gray', 'Mutineers'),
  ('Ben', 'David Gray', 'Mutineers (signed)'),
  ('Ben', 'David Gray', 'Skellig'),
  ('Ben', 'David Gray', 'white Ladder (Dlx 20th Ann Boxset)'),
  ('Ben', 'De La Soul', 'and the Anonymous Nobody'),
  ('Ben', 'Death in Vegas', 'Dirge'),
  ('Ben', 'Delays', 'Faded Seaside Glamour - Dlx Ltd Ed Orange vinyl'),
  ('Ben', 'Departure', 'All Mapped Out (Remixes) Promo'),
  ('Ben', 'Depeche Mode', 'Violator'),
  ('Ben', 'Doves', 'Cally/Lean Into The Wind 10" RSD ''25'),
  ('Ben', 'Doves', 'Catch the sun (promo)'),
  ('Ben', 'Doves', 'Caught by the river'),
  ('Ben', 'Doves', 'Cedar Ep (original – before signed)'),
  ('Ben', 'Doves', 'Constellations For The Lonely (White vinyl)'),
  ('Ben', 'Doves', 'Kingdom of Rust - 2022 Ltd Ed Numbered Colour Vinyl'),
  ('Ben', 'Doves', 'Lost Souls - 2019 Ltd Colour Vinyl'),
  ('Ben', 'Doves', 'Lost Souls - 2019 Ltd Colour Vinyl'),
  ('Ben', 'Doves', 'M62 Song Remix'),
  ('Ben', 'Doves', 'Pounding'),
  ('Ben', 'Doves', 'Some Cities - 2019 Ltd Colour Vinyl'),
  ('Ben', 'Doves', 'Some Cities - original'),
  ('Ben', 'Doves', 'The Last Broadcast - 2019 Ltd Colour Vinyl'),
  ('Ben', 'Doves', 'The Last Broadcast - 2019 Ltd Colour Vinyl'),
  ('Ben', 'Doves', 'The Universal Want'),
  ('Ben', 'Doves', 'There goes the fear'),
  ('Ben', 'Doves', 'There goes the fear – while label'),
  ('Ben', 'Echo & The Bunnymen', 'Never Stop 12"'),
  ('Ben', 'Echo & The Bunnymen', 'Porcupine'),
  ('Ben', 'Echo & The Bunnymen', 'The John Peel Sessions 1979-83'),
  ('Ben', 'Echo & The Bunnymen', 'Crocodiles, 2021 Coloured vinyl'),
  ('Ben', 'Echo & The Bunnymen', 'Heaven Up Here'),
  ('Ben', 'Echo & The Bunnymen', 'Live in Liverpool - RSD excl clear x 2 vinyl'),
  ('Ben', 'Echo & The Bunnymen', 'Ocean Rain, 2021 Coloured vinyl'),
  ('Ben', 'Ed Harcourt', 'From Every Sphere (album)'),
  ('Ben', 'Editors', 'An End Has A Start'),
  ('Ben', 'Editors', 'Blood'),
  ('Ben', 'Editors', 'EBM (Ltd Ed crystal clear)'),
  ('Ben', 'Editors', 'The Back Room'),
  ('Ben', 'Elbow', 'Giants of All Sizes'),
  ('Ben', 'Elbow', 'Audio Vertigo (Mirrorboard Ltd clear vinyl)'),
  ('Ben', 'Elbow', 'Dexter & Sinister 10"'),
  ('Ben', 'Elbow', 'EP 5 - Audio Vertigo Echo (Ltd white vinyl)'),
  ('Ben', 'Elbow', 'Flying Dream 1 (ltd green vinyl)'),
  ('Ben', 'Elbow', 'Little Fictions (White Vinyl - Indie Store excl)'),
  ('Ben', 'Elbow', 'Live At The Ritz (acoustic)'),
  ('Ben', 'Elbow', 'Open Arms'),
  ('Ben', 'Elbow', 'The Any Day Now EP 10" (RSD ''21)'),
  ('Ben', 'Elbow', 'the definitive album box set x 7 (…build a rocket boys)'),
  ('Ben', 'Elbow', 'The Newborn EP 10" (RSD ''21)'),
  ('Ben', 'Elbow', 'World Café Live EP'),
  ('Ben', 'Elton John', 'Goodbye Yellow Brick Road'),
  ('Ben', 'English Teacher', 'This Could Be Texas (Green Vinyl)'),
  ('Ben', 'Eric Matthews', 'It''s Heavy in Here (Blue vinyl)'),
  ('Ben', 'Ethel Cain', 'Willoughby Tucker, I will Always Love You (Indie Excl)'),
  ('Ben', 'Everything Everything', 'Re-animator'),
  ('Ben', 'Felix Riebl', 'Everyday Amen (Test Pressing)'),
  ('Ben', 'Felix Riebl', 'Paper Doors'),
  ('Ben', 'Fleet Foxes', 'Shore (ltd Indies Crystal clear vinyl)'),
  ('Ben', 'Florence & The Machine', 'Everybody Scream (Translucent Green 2 LP)'),
  ('Ben', 'Flowered Up', 'A Life With Brian (Ltd Ed Double Coloured Vinyl)'),
  ('Ben', 'Flowered Up', 'Weekender 12" 2021 Ed'),
  ('Ben', 'Foals', 'Everything Not Save Will Be Lost Part 1'),
  ('Ben', 'Foals', 'Everything Not Save Will Be Lost Part 2 (Ltd Orange Vinyl)'),
  ('Ben', 'Foals', 'Holy Fire'),
  ('Ben', 'Foals', 'Life Is Yours (Excl Dlx 2LP ncl signed art card- marbled vinyl and black vinyl demos)'),
  ('Ben', 'Foals', 'Total Life Forever'),
  ('Ben', 'Foals', 'What Went Down'),
  ('Ben', 'Fontaine’s DC', 'A Hero''s Death (Dlx Ed)'),
  ('Ben', 'Fontaine’s DC', 'Cello (Nick Drake) 7"'),
  ('Ben', 'Fontaine’s DC', 'Darklands'),
  ('Ben', 'Fontaine’s DC - It’s Amazing…/Before You I Just Forget  (Neon Vinyl Ltd Ed 2', '000) 7"'),
  ('Ben', 'Fontaine’s DC', 'Skinty Fia (Dlx Ed 45rpm Double vinyl)'),
  ('Ben', 'Fontaine’s DC', 'Skinty Fia Sessions (Ltd Ed Rough Trade 10" vinyl)'),
  ('Ben', 'Fontaine’s DC -Romance', '(Deluxe Edition, Limited Edition, Stereo, Triple Gatefold)'),
  ('Ben', 'Fontaine’s DC -Romance', '(Limited Edition, Numbered, White Label, Stereo, First Pressing)'),
  ('Ben', 'Fontaine’s DC', 'Dogrel (Ltd Ed Rough Trade Marble Swirl Colour)'),
  ('Ben', 'Fontaine’s DC', 'Live at Kilmainham Gaol (RSD ''21)'),
  ('Ben', 'Formation', 'Look At The Powerful People'),
  ('Ben', 'Frankie Goes to Hollywood', 'Power of Love'),
  ('Ben', 'Frankie Goes to Hollywood', 'Welcome to the Pleasure Dome'),
  ('Ben', 'Frankie Goes to Hollywood', 'Welcome to the pleasure dome (album)'),
  ('Ben', 'Friendly Fires', 'Friendly Fires (15th Ann Ltd Ed Silver)'),
  ('Ben', 'Friendly Fires', 'Paris (15th Ann Ltd Ed Gold)'),
  ('Ben', 'Fun Lovin'' Criminals', 'FLC'),
  ('Ben', 'Fun Lovin'' Criminals', 'Loco / Bump'),
  ('Ben', 'Global Communication', 'The Remixes x 2'),
  ('Ben', 'Goldfrapp', 'Seventh Tree (2021 reissue yellow vinyl)'),
  ('Ben', 'Gorillaz', 'Clint Eastwood'),
  ('Ben', 'Gorillaz', 'gorrilaz (album)'),
  ('Ben', 'Gorillaz', 'Promo Remixes 3 tracks'),
  ('Ben', 'Gorillaz', 'Tomorrow Comes Today'),
  ('Ben', 'Grant Lee Buffalo', 'Copperopolis 2023 Remastered Clear vinyl'),
  ('Ben', 'Grant Lee Buffalo', 'Fuzzy 2023 Remastered'),
  ('Ben', 'Grant Lee Buffalo', 'Jubilee 2023 Remastered Clear vinyl'),
  ('Ben', 'Grant Lee Buffalo', 'Mighty Joe Moon 2023 Remastered'),
  ('Ben', 'Guillemots', 'We''re Here'),
  ('Ben', 'Gut Health', 'Stiletto'),
  ('Ben', 'Hamilton Leithauser', 'Live at Café Carlyle'),
  ('Ben', 'HIM', 'Razorblade Romance (signed)'),
  ('Ben', 'Hookworms', 'Microshift x2'),
  ('Ben', 'Hope & Social', 'Feel'),
  ('Ben', 'Hope of the States', 'Long Waits in A&E EP'),
  ('Ben', 'Hope of the States', 'The Lost Riots (Nat'' Album Day Ltd Ed Battered Metal Colour)'),
  ('Ben', 'Hot Chip', 'Colours'),
  ('Ben', 'House of Love', 'Audience With The Mind'),
  ('Ben', 'House of Love', 'Babe Rainbow'),
  ('Ben', 'House of Love', 'Butterfly Album'),
  ('Ben', 'House of Love', 'Crush Me'),
  ('Ben', 'House of Love', 'Crush Me demo / Into the tunnel'),
  ('Ben', 'House of Love', 'Debut Album (30th Ann 2 LP)'),
  ('Ben', 'Inspiral Carpets', 'Revenge of the Goldfish (30th Ann'' Ltd Transparent Orange)'),
  ('Ben', 'Interpol', 'Our Love to Admire'),
  ('Ben', 'Interpol', 'Turn On The Bright Lights'),
  ('Ben', 'James', 'Laid (remastered)'),
  ('Ben', 'James', 'Living in Extraordinary Times'),
  ('Ben', 'James', 'Seven'),
  ('Ben', 'James', 'Whiplash'),
  ('Ben', 'James', 'Yummy'),
  ('Ben', 'Jeff Buckley', 'Grace (Ltd Gold Vinyl)'),
  ('Ben', 'Joy Division', 'Closer (remasters)'),
  ('Ben', 'Joy Division', 'Unknown Pleasures (remasters)'),
  ('Ben', 'Julian Cope', 'Peggy Suicide'),
  ('Ben', 'Julian Cope', 'Saint Julian'),
  ('Ben', 'Jungle', 'Loving in Stereo'),
  ('Ben', 'Jungle', 'Volcano'),
  ('Ben', 'Kent', 'Hagnesta Hill 2023'),
  ('Ben', 'Kent', 'Isola 2023'),
  ('Ben', 'Kevin Mark Trail', 'Perspective'),
  ('Ben', 'Kraftwerk', 'Aerodynamik (Remixes Promo)'),
  ('Ben', 'Lanterns On The Lake', 'Spook The Heard (x2)'),
  ('Ben', 'Lanterns On The Lake', 'Versions of Us (Orange Vinyl Ed)'),
  ('Ben', 'Laufey', 'A Matter of Time (Indie Excl Rouge Vinyl/Autumn Ed'')'),
  ('Ben', 'Led Zeppelin', 'Led Zeppelin (Dlx 3xLP Set 180g Vinyl)'),
  ('Ben', 'Led Zeppelin', 'Led Zeppelin II (180g Vinyl)'),
  ('Ben', 'Led Zeppelin', 'Led Zeppelin III (180g Vinyl)'),
  ('Ben', 'Led Zeppelin', 'Led Zeppelin IV (180g Vinyl)'),
  ('Ben', 'Led Zeppelin', 'Physical Graffiti (40th Ann 180g Vinyl)'),
  ('Ben', 'Lhooq', 'Losing hand – promo'),
  ('Ben', 'Lightning Seeds', 'Pure/All I Want 10" Single (35th Ann'')'),
  ('Ben', 'Lily Allen', 'LDN remixes (promo)'),
  ('Ben', 'Linoleum', 'Dissent'),
  ('Ben', 'Little Simz', 'Lotus (Midnight Bloom Excl Colour)'),
  ('Ben', 'Little Simz', 'No Thank You (Clear Vinyl)'),
  ('Ben', 'Little Simz', 'Sometimes I Might Be Introvert (indies coloured vinyl)'),
  ('Ben', 'Lloyd Cole & The Commotions', 'Rattlesnakes'),
  ('Ben', 'Lloyd Cole', 'Easy Pieces (1st UK Press)'),
  ('Ben', 'Lloyd Cole', 'Lloyd Cole (Orginal UK Press)'),
  ('Ben', 'Longpigs', 'Mobile Home (2021 reissue clear vinyl)'),
  ('Ben', 'Longpigs', 'The Sun Is Often Out (2020 reissue blue vinyl)'),
  ('Ben', 'Longstone', 'Live in NY'),
  ('Ben', 'Low Island', 'Life In Minature (Signed White Vinyl)'),
  ('Ben', 'Mansun', 'Attack of the Grey Latern (2018 ltd ed purple vinyl)'),
  ('Ben', 'Mansun', 'I can only disappoint you'),
  ('Ben', 'Mansun', 'Little Kix (album)'),
  ('Ben', 'Mansun', 'Six (ltd ed 2019 ltd ed dble blue)'),
  ('Ben', 'Maps', 'Start Something'),
  ('Ben', 'Mark Hollis', 'Mark Hollis'),
  ('Ben', 'Matthew J', 'Friendly Fire (remix)'),
  ('Ben', 'McAlmont & Butler', 'The Yes Recordings (Ltd Ed 1000 copies) 12"'),
  ('Ben', 'Mew', 'Frengers'),
  ('Ben', 'Midnight Oil', 'Diesel & Dust'),
  ('Ben', 'Mild Orange', 'Foreplay LP'),
  ('Ben', 'Mild Orange', 'Looking For Space'),
  ('Ben', 'Mild Orange', 'Mild Orange (signed)'),
  ('Ben', 'Milltown Brothers', 'Apple Green EP'),
  ('Ben', 'Milltown Brothers', 'Slinky'),
  ('Ben', 'Mimi Gilbert', 'Grew Inside The Water'),
  ('Ben', 'Mulu', 'Desire'),
  ('Ben', 'Mulu', 'Desire'),
  ('Ben', 'Mulu', 'Desire – remixes'),
  ('Ben', 'Mulu', 'Desire (white label)'),
  ('Ben', 'Mulu', 'Desire Remixes (white label) x 2'),
  ('Ben', 'Mulu', 'Pussy Cat'),
  ('Ben', 'Mulu', 'Pussy Cat'),
  ('Ben', 'Mulu', 'Pussy Cat – mixes (white label)'),
  ('Ben', 'Neil Finn', 'Dizzy Heights'),
  ('Ben', 'Neneh Cherry', 'Broken Politics (signed)'),
  ('Ben', 'New Fads', 'Body Exit Mind'),
  ('Ben', 'New Fads', 'Love It All'),
  ('Ben', 'New Fads', 'These foolish things'),
  ('Ben', 'New Fads', 'These foolish things'),
  ('Ben', 'New Order -+ Liam Gillick', 'So It Goes Live MIF  (x 3 Coloured vinyl)'),
  ('Ben', 'New Order Music Complete', '8 piece dlx coloured vinyl box set'),
  ('Ben', 'New Order', 'Bizarre Love Triangle (2024 Reissue 12")'),
  ('Ben', 'New Order', 'Blue Monday 2020 12"'),
  ('Ben', 'New Order', 'Blue Monday 88 2023 Reissue 12"'),
  ('Ben', 'New Order', 'Brotherhood (2009 resissue)'),
  ('Ben', 'New Order', 'Brotherhood (2024 Definitive Ed Boxset)'),
  ('Ben', 'New Order', 'Ceremony / In A Lonely Place 2019 12" Green Cover'),
  ('Ben', 'New Order', 'Ceremony / In A Lonely Place 2019 12"White Cover'),
  ('Ben', 'New Order', 'Confusion'),
  ('Ben', 'New Order', 'Confusion 2020 12"'),
  ('Ben', 'New Order', 'Everythings Gone Green 2019 12"'),
  ('Ben', 'New Order', 'Fine Time'),
  ('Ben', 'New Order', 'Low Life (180g 2009 vinyl)'),
  ('Ben', 'New Order', 'Low Life (2022 Definitive Ed Boxset)'),
  ('Ben', 'New Order', 'Movement (2019 Definitive Ed Boxset)'),
  ('Ben', 'New Order', 'Murder 2020 12"'),
  ('Ben', 'New Order', 'Music Complete'),
  ('Ben', 'New Order', 'Music Complete (Ltd Ed Clear Vinyl)'),
  ('Ben', 'New Order', 'NOM15 (Triple Vinyl Live Album)'),
  ('Ben', 'New Order', 'Perfect Kiss 2022 12" Clear Vinyl'),
  ('Ben', 'New Order', 'Power Corruption & Lies (2020 Definitive Ed Boxset)'),
  ('Ben', 'New Order', 'Run 2'),
  ('Ben', 'New Order', 'Shellshock 2022 12"'),
  ('Ben', 'New Order', 'Singles (Box - Remastered)'),
  ('Ben', 'New Order', 'State of The Nation (2024 Reissue 12")'),
  ('Ben', 'New Order', 'Sub-Culture 2022 12"'),
  ('Ben', 'New Order', 'Substance 1987 2023 Reissue (2 x Coloured LP)'),
  ('Ben', 'New Order', 'Technique'),
  ('Ben', 'New Order', 'Temptation'),
  ('Ben', 'New Order', 'Temptation 2019 12"'),
  ('Ben', 'New Order', 'Thieves Like Us'),
  ('Ben', 'New Order', 'Thieves Like Us 2020 12"'),
  ('Ben', 'New Order', 'Touched By The Hand of God (2024 Reissue 12")'),
  ('Ben', 'New Order', 'True Faith 2023 Reissue 12"'),
  ('Ben', 'New Order', 'True Faith Remix 2023 Reissue 12"'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Ghosteen'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Give Us A Kiss 10" x2'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Idiot Prayer, Alone at Alexandra Palace'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Live from KCRW'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Live in Copenhagen EP'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Push The Sky Away (boxset)'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Push The Sky Away (Ltd 7")'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Push The Sky Away (std)'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Skeleton Tree'),
  ('Ben', 'Nick Cave & The Bad Seeds', 'Wild God (Ltd Ed Clear vinyl)'),
  ('Ben', 'Nick Cave & Warren Ellis', 'Australian Carnage (live at SOH)'),
  ('Ben', 'Nick Cave & Warren Ellis', 'Carnage'),
  ('Ben', 'Nick Drake', 'Pink Moon'),
  ('Ben', 'Ocean Colour Scene', 'Sway'),
  ('Ben', 'Pet Shop Boys', 'Electric'),
  ('Ben', 'Phil Collins', 'Face Value'),
  ('Ben', 'Phil Collins', 'Hello I must be going'),
  ('Ben', 'Phoebe Go', 'Marmalade'),
  ('Ben', 'Phoebe Go', 'Player EP'),
  ('Ben', 'Pink Floyd', 'Delicate Sound of Thunder – live album'),
  ('Ben', 'Pixies', 'Doolittle'),
  ('Ben', 'Pixies', 'Here comes your man'),
  ('Ben', 'Power of Dreams', 'A little piece of God'),
  ('Ben', 'Power of Dreams', 'immigrants Emigrants & Me'),
  ('Ben', 'Power of Dreams', 'Second Sun – EP'),
  ('Ben', 'Power of Dreams', 'Stay'),
  ('Ben', 'Power of Dreams', 'There I go again'),
  ('Ben', 'Public Service Broadcasting', 'Bright Magic (ltd ed brown vinyl)'),
  ('Ben', 'Public Service Broadcasting', 'Every Valley'),
  ('Ben', 'Public Service Broadcasting', 'Inform Educate Entertain'),
  ('Ben', 'Public Service Broadcasting', 'Live At Brixton'),
  ('Ben', 'Public Service Broadcasting', 'The Last Flight (Limited Edition, Picture Disc, Zoetrope)'),
  ('Ben', 'Public Service Broadcasting', 'The Race for Space'),
  ('Ben', 'Puressence', 'Only Forever LP'),
  ('Ben', 'Puressence', 'Puressence LP'),
  ('Ben', 'Radiohead', 'The Bends'),
  ('Ben', 'Radiohead', 'Amnesiac (album)'),
  ('Ben', 'Radiohead', 'Hail To The Thief'),
  ('Ben', 'Radiohead', 'Hail To The Thief Live Recordings 2003-09 (Ltd Ed Red Vinyl)'),
  ('Ben', 'Radiohead', 'Idioteque Kid A taster (promo) x2'),
  ('Ben', 'Radiohead', 'In Rainbows'),
  ('Ben', 'Radiohead', 'Kid A (album)'),
  ('Ben', 'Radiohead', 'Ok Computer (remaster triple vinyl)'),
  ('Ben', 'Rain', 'Lemon Stone Desired'),
  ('Ben', 'Rain', 'Taste of Rain'),
  ('Ben', 'Red Box', 'Lean on Me'),
  ('Ben', 'Red Skins', 'It Can Be Done – EP'),
  ('Ben', 'Reverb', 'Time Lapse'),
  ('Ben', 'Robert Plant', 'Band of Joy'),
  ('Ben', 'Rod Stewart', 'Every Picture Tells a Story'),
  ('Ben', 'Ryan Adams', 'Gold'),
  ('Ben', 'Scheer', 'Facing the Wrong Way'),
  ('Ben', 'Schtum', 'Corrupt cop x2'),
  ('Ben', 'Schtum', 'New Year Dawning x 2'),
  ('Ben', 'Sea Power', 'Everything Was Forever'),
  ('Ben', 'Shere Khan', 'Ghost'),
  ('Ben', 'Shere Khan', 'Midnight'),
  ('Ben', 'Shirley Bassey & Away Team', 'Where do i begin x2'),
  ('Ben', 'Sigur Ros', 'In A frozen Sea – Ltd Edition – 8 x album vinyl and photo album -'),
  ('Ben', 'Sigur Ros', 'Agaetis Byrjun (Audiophile Quality)'),
  ('Ben', 'Sigur Ros', 'Ba ba ti Ki Di Do'),
  ('Ben', 'Sigur Ros', 'Brackets Alb (Audiophile Quality)'),
  ('Ben', 'Sigur Ros', 'Hoppipolla'),
  ('Ben', 'Sigur Ros', 'In A Frozen Sea vinyl boxset (A Year with Sigur Ros) Ltd Ed 5000'),
  ('Ben', 'Sigur Ros', 'Saeglopur'),
  ('Ben', 'Sigur Ros', 'Takk x3'),
  ('Ben', 'Sigur Ros', 'Von'),
  ('Ben', 'Simple Minds', 'Let it all come down'),
  ('Ben', 'Simple Minds', 'Live in the city of life'),
  ('Ben', 'Simple Minds', 'New Gold Dream (81/82/83/84)'),
  ('Ben', 'Simple Minds', 'Once upon a time'),
  ('Ben', 'Simple Minds', 'Real to Real Cacophony'),
  ('Ben', 'Simple Minds', 'Sparkle in the rain x2'),
  ('Ben', 'Simple Minds', 'Street fighting years'),
  ('Ben', 'Six By Seven', 'The Things We Make (Ltd Ed Blue Vinyl)'),
  ('Ben', 'Six by Seven', 'European Me'),
  ('Ben', 'Six by Seven', 'The Closer You Get'),
  ('Ben', 'Six by Seven', 'The Way I Feel Today Dlx 2 LP (RSD ''21)'),
  ('Ben', 'Spacey Jane', 'Here Comes Everybody (JB Excl Orange Vinyl)'),
  ('Ben', 'Spacey Jane', 'Here Comes Everybody (Ltd Alt'' Cover - 500 copies - Signed)'),
  ('Ben', 'Spacey Jane', 'Here Comes Everybody (Ltd Spotify Orange and Clear Vinyl) x2'),
  ('Ben', 'Spacey Jane', 'If That Makes Sense (Ltd Green & White Love is a Garden Vinyl)'),
  ('Ben', 'Spacey Jane', 'In The Slight EP (Ltd Colour Vinyl)'),
  ('Ben', 'Spacey Jane', 'No Way To Treat An Animal EP (Ltd Colour Vinyl)'),
  ('Ben', 'Spacey Jane', 'Sunlight (Ann'' boxset)'),
  ('Ben', 'Spacey Jane', 'Sunlight (Ltd Colour Vinyl)'),
  ('Ben', 'Spiritualized', 'Any way that you want me – remix'),
  ('Ben', 'Spiritualized', 'Come Together – remixes'),
  ('Ben', 'Spiritualized', 'I think I''m in Love (Chemical Bros) – white label'),
  ('Ben', 'Spiritualized', 'I think I''m love'),
  ('Ben', 'Spiritualized', 'Ladies Gentlemen – album'),
  ('Ben', 'Spiritualized', 'Lay back in the sun (promo)'),
  ('Ben', 'Spiritualized', 'Let it Flow'),
  ('Ben', 'Spiritualized', 'Pure Phase Tones for Djs x2'),
  ('Ben', 'Spiritualized', 'white label'),
  ('Ben', 'Spirituralized', 'Live at the royal albert hall – album'),
  ('Ben', 'Starsailor', 'Four to the Floor 10"'),
  ('Ben', 'Starsailor', 'Four to the Floor Remixes (promo) x 2'),
  ('Ben', 'Starsailor', 'Four to the Floor Remixes (white label promo)'),
  ('Ben', 'Starsailor', 'Good Souls (promo)'),
  ('Ben', 'Starsailor', 'Love is Here'),
  ('Ben', 'Starsailor', 'On the Outside'),
  ('Ben', 'Starsailor', 'Silence is Easy'),
  ('Ben', 'Stephen Fretwell', '8 Songs'),
  ('Ben', 'Stornoway', 'Beachcomber Windowsill'),
  ('Ben', 'Stornoway', 'Best of Unplucked (Ltd Ed Eco Mix LP)'),
  ('Ben', 'Stornoway', 'Dig The Mountain'),
  ('Ben', 'Stornoway', 'Tales From Terra Firma'),
  ('Ben', 'Sulphur', '2CV'),
  ('Ben', 'Superstar', 'Palm Tree (2 LP Yellow vinyl 2022 reissue)'),
  ('Ben', 'Talk Talk', 'It’s My Life'),
  ('Ben', 'Talk Talk', 'Laughing Stock'),
  ('Ben', 'Talk Talk', 'Spirit of Eden  incl DVD'),
  ('Ben', 'Talk Talk', 'The Colour of Spring incl DVD'),
  ('Ben', 'Talk Talk', 'The Party''s Over'),
  ('Ben', 'Tears for Fears', 'Live At Massey Hall, 1985 x2 LP (RSD ''21)'),
  ('Ben', 'Tears for fears', 'Seeds of love'),
  ('Ben', 'Tears for Fears', 'Songs from the big chair'),
  ('Ben', 'Tears for fears', 'The Hurting'),
  ('Ben', 'Television', 'Marquee Moon'),
  ('Ben', 'The 4 of Us', 'I miss you'),
  ('Ben', 'The Art of Noise', 'Peter Gunn'),
  ('Ben', 'The Beatles', '1 (album)'),
  ('Ben', 'The Blue Nile', 'Hats'),
  ('Ben', 'The Bolshoi', 'Lindy''s Party Album'),
  ('Ben', 'The Boxer Rebellion', 'Cold Still (Heavyweight Green)'),
  ('Ben', 'The Boxer Rebellion', 'Exits (Heavyweight red vinyl)'),
  ('Ben', 'The Boxer Rebellion', 'Open Arms EP (Cream Vinyl)'),
  ('Ben', 'The Boxer Rebellion', 'Promises (Heavyweight Sea Blue)'),
  ('Ben', 'The Boxer Rebellion', 'Union (Heavyweight Bronze )'),
  ('Ben', 'The Boxer Rebellion', 'Ghost Alive (Heavyweight White)'),
  ('Ben', 'The Catherine Wheel', 'Wishville'),
  ('Ben', 'The Charlatans', 'Wonderland (RSD ''25 Ltd Ed 2LP White and Red)'),
  ('Ben', 'The Church', 'Gold Afternoon Fix (ltd ed gold vinyl)'),
  ('Ben', 'The Church', 'Heyday (Red Vinyl 2024 press)'),
  ('Ben', 'The Church', 'Priest = Aura (ltd ed white & black swirled vinyl)'),
  ('Ben', 'The Church', 'Starfish ltd ed white vinyl'),
  ('Ben', 'The Cure', 'Disintegration (2010 remastered 2 LP)'),
  ('Ben', 'The Cure', 'Songs of A Lost World (Marble Stone Heavy Bio Vinyl)'),
  ('Ben', 'The Horrors', 'V'),
  ('Ben', 'The Housemartins', 'London 0 Hull 4'),
  ('Ben', 'The Lucid Dream', 'Dippy EP'),
  ('Ben', 'The Maccabees', 'Given to the Wild (Translucent Orange)'),
  ('Ben', 'The Maccabees', 'Marks To Prove It (10th Ann'' Dlx LP)'),
  ('Ben', 'The Mighty Lemon Drops', 'Happy Head'),
  ('Ben', 'The Mighty Lemon Drops', 'The Janice Long Session'),
  ('Ben', 'The Mighty Lemon Drops', 'The other side to you (while label)'),
  ('Ben', 'The Mighty Lemon Drops', 'World Without End'),
  ('Ben', 'The Open', 'Close my eyes'),
  ('Ben', 'The Pale Fountains', 'From Across the Kitchen Table'),
  ('Ben', 'The Pale Fountains', 'From Across the Kitchen Table'),
  ('Ben', 'The Pale Fountains', 'Longshot For Your Love'),
  ('Ben', 'The Rolling Stones', '40 Licks (album) – limited edition box set'),
  ('Ben', 'The Stone Roses', 'The Stone Roses (Transparent vinyl)'),
  ('Ben', 'The Strokes', 'Future Present Past EP'),
  ('Ben', 'The Sundays', 'Reading Writing and Arithmetic (rough 148 LP UK)'),
  ('Ben', 'The Teardrop Explodes', 'Kilimanjaro'),
  ('Ben', 'The Tragically Hip', 'Small Town Bring Down'),
  ('Ben', 'The Triffids', 'Born Sandy Devotional (Ltd Ed Yellow Vinyl)'),
  ('Ben', 'The Twilight Sad', 'Fourteen Autumns & Fifteen Winters'),
  ('Ben', 'The Twilight Sad', 'It Won''t be Like This…(Ltd Blue vinyl)'),
  ('Ben', 'The Twilight Sad', 'Nobody Wants To Be Here…'),
  ('Ben', 'The Upsetters', 'Blackboard Jungle Dub'),
  ('Ben', 'The Verve', 'A Northern Soul (Remastered)'),
  ('Ben', 'The Verve', 'A Storm In Heaven (Remastered)'),
  ('Ben', 'The Verve', 'No Come Down (B-sides & Outtakes, 30th Ann'' excl)'),
  ('Ben', 'The Verve', 'Urban Hyms (Remastered)'),
  ('Ben', 'The Verve', 'Voyager 1 (RSD ''25 reissue)'),
  ('Ben', 'The War on Drugs', 'Lost in the Dream'),
  ('Ben', 'The Waterboys', 'A Pagan Place (US pressing)'),
  ('Ben', 'The Waterboys', 'Fishermans Blues (Ltd Ed Yellow Matter Custard 180g)'),
  ('Ben', 'The Waterboys', 'Modern Blues (Signed)'),
  ('Ben', 'The Waterboys', 'This is The Sea (Signed)'),
  ('Ben', 'The Who', 'Live at Leeds (album)'),
  ('Ben', 'The Who', 'Who''s Next'),
  ('Ben', 'The Wonder Stuff', 'Hup (album)'),
  ('Ben', 'The Wood Children', 'Sweets for the Blind'),
  ('Ben', 'Then Jerico', 'First (album)'),
  ('Ben', 'Then Jerico', 'The big area'),
  ('Ben', 'This Picture', 'Highrise – promo'),
  ('Ben', 'This Picture', 'maniac man promo'),
  ('Ben', 'This Picture', 'Naked Rain'),
  ('Ben', 'This Picture', 'With you I can never win'),
  ('Ben', 'Thompson Twins', 'Revolution'),
  ('Ben', 'Thousand Yard Stare', 'Hands on – album'),
  ('Ben', 'Todd Terje', 'It''s Album Time'),
  ('Ben', 'Toots & the Maytals', 'Funky Kingston - RSD ed'),
  ('Ben', 'Travis', 'Where You Stand'),
  ('Ben', 'Turin Brakes', 'Ether Song (Ltd Ed Blue vinyl 20th Ann 2LP)'),
  ('Ben', 'Turin Brakes', 'Invisible Storm'),
  ('Ben', 'Turin Brakes', 'Lost Property'),
  ('Ben', 'Turin Brakes', 'Spacehopper (Ltd Ed Transparent Blue Vinyl)'),
  ('Ben', 'Turin Brakes', 'The Optimist LP (20th Ann'' Amber vinyl)'),
  ('Ben', 'Turin Brakes', 'We Were Here'),
  ('Ben', 'Turin Brakes', 'Wide Eyed Nowhere (ltd ed White Vinyl)'),
  ('Ben', 'Twilight Sad', 'Fourteen Austumns & Fifteen Winters'),
  ('Ben', 'U2', 'Fire - 40th Ann Edition - RSD'),
  ('Ben', 'U2', 'Achtung Baby (30th Ann'' Spec Ed Vinyl)'),
  ('Ben', 'U2', 'All I want is you'),
  ('Ben', 'U2', 'Articulate Speech of the Heart – triple live album'),
  ('Ben', 'U2', 'Boy (album)'),
  ('Ben', 'U2', 'Boy (Remastered audio 2009)'),
  ('Ben', 'U2', 'Desire'),
  ('Ben', 'U2', 'Discoteque – triple vinyl'),
  ('Ben', 'U2', 'Fire (maxi single)'),
  ('Ben', 'U2', 'New Years Day'),
  ('Ben', 'U2', 'October (Remastered audio 2009)'),
  ('Ben', 'U2', 'The Joshua Tree, Super Dlx Vinyl Boxset'),
  ('Ben', 'U2', 'The Unforgettable Fire – maxi single'),
  ('Ben', 'U2', 'The Unforgettable Fire (Remastered audio 2009)'),
  ('Ben', 'U2', 'Two Hearts Beat as One (club version)'),
  ('Ben', 'U2', 'Under A Blood Red Sky (Remastered audio 2009)'),
  ('Ben', 'U2', 'War (album)'),
  ('Ben', 'U2', 'War (Remastered audio 2009)'),
  ('Ben', 'U2', 'Wide Awake in America'),
  ('Ben', 'U2', 'Zooropa (2018 remaster - deluxe foil board gatefold package)'),
  ('Ben', 'Underworld', 'Beaucoup Fish (2025 reissue)'),
  ('Ben', 'Underworld', 'dubbnobasswithmyheadman (2025 reissue)'),
  ('Ben', 'Underworld', 'Second Toughest in the Infants (2025 reissue)'),
  ('Ben', 'Van Morrison', 'Astral Weeks'),
  ('Ben', 'Various: Fontaines DC x Massive Attack x Young Fathers (12" In Benefit of Docs wout Borders)', 'Various: Fontaines DC x Massive Attack x Young Fathers (12" In Benefit of Docs wout Borders)'),
  ('Ben', 'Voyage to the Cosmic Underworld', 'Incl Reverb'),
  ('Ben', 'Whipping Boy', 'Heartworm (2021 reissue)'),
  ('Ben', 'Wolf Alice', 'Blue Weekend (black std)'),
  ('Ben', 'World Party', 'Goodbye Jumbo'),
  ('Ben', 'Wu Lyf', 'Go Tell Fire to the Mountain - Clear vinyl - RSD'),
  ('Ben', 'Young Fathers', 'Heavy Heavy Dlx Ltd White with Excl Art etc')
;
